### PR TITLE
Hooks

### PR DESCRIPTION
**Pull request by owahab**
Adding delayed_job hook execution to delayed_paperclip

### CODE REVIEW

**Comment by owahab** [comment]
Unfortunately, this is built on top of another feature.

**Comment by jstorimer** [comment]
Right, but once we fix #27 hopefully we can merge both.

**Comment by Bertg** [comment]
Sorry for the inconvenience, but could you split these 2 changes and rebase them on the current master?

There have been quite some changes that should be taken into account...

**Comment by owahab** [comment]
Will do. But kinda have a question: are you at all willing to pull?
It has been a month and you're not doing anything to the broken tests and now you're simply asking me to rebase?
And of course after the rebase I'd still wait for the infamous #27 to be fixed, no?

**Comment by jstorimer** [comment]
I'd be willing to merge this if you split it from #21. I haven't wanted to merge changes in to the master branch while the refactoring from @Bertg was happening. And #27 is now fixed :)

**Comment by Bertg** [comment]
Hey @owahab, are you still working on the rebase of these features? Or should I find someone else to do these?

**Pull request closed without merging**
