### PR TITLE
after_save does not guarantee that the DB is in a permanent state

### PR DESCRIPTION
**Pull request by Bertg**
This is relevant to issue #22

We currently trigger the background task as such: 

``` ruby
after_save  :"enqueue_job_for_#{name}"
```

At this point (when creating a record) there is nothing in the DB according to processes using a different connection (default mysql setting). only after the commit we should trigger the task.

``` ruby
after_commit  :"enqueue_job_for_#{name}"
```

See: http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html

### CODE REVIEW

**Comment by bigfleet** [comment]
@Bertg If this were merged, would delayed_paperclip become Rails 3 compatible only?

**Comment by Bertg** [comment]
Yes, yes it would, I was not aware of this. But it could be easily covered with a rails version check...
Let me get on to that ;)

**Comment by Bertg** [comment]
After_commit won't work straight out of the box sadly. The object loses it's dirty info between the after_save and after_commit.

I would need to re-architect the callbacks to get this working. Where there are now several callbacks defined for each attachment, we could join enqueue_job_for_*, *_processing! methods into each one callback. in A simmilar way paperclip does it's save_attached_files in one call.

Is there an intrest in this rewrite?

**Comment by jstorimer** [comment]
It's unfortunate that this doesn't work as expected out of the box. 

On projects that I've worked on before we've gotten around this by actually assigning the #changes to an attr_accessor in an after_save callback, then accessing them (and niling them) in an after_commit callback. 

@Bertg if you can get this to work happily with Rails 3 then I'd be happy to merge it. I'm also not against the idea of releasing a new version that is Rails 3 only and just maintaining that going forward if that's the path of least resistance.

**Comment by Bertg** [comment]
Ok, I did a first refactoring here: https://github.com/Bertg/delayed_paperclip/tree/refactoring

If you like this approach let me know. Then we can do some (regression) testing and publish it later on.

**Comment by Bertg** [comment]
Closing this. See pull request 29 (https://github.com/jstorimer/delayed_paperclip/pull/29)

**Pull request closed without merging**
