### PR TITLE
[Fix] most_appropiate_url changed to be part of Paperclip::UrlGenerator

### PR DESCRIPTION
**Pull request by tommeier**
... tested across rails versions and added Rails 3.2 to test suite. Paperclip version bumped to 2.7

```
bundle install
bundle exec rake appraisal:install
bundle exec rake appraisal test
```

All working across rails versions.

Could probably do with a better method than monkey patching the Paperclip::UrlGenerator method. But I didn't want to generate a whole new UrlGenerator and pass it in...

The better method would be to create a new Paperclip::UrlGenerator as this is, subclass the Paperclip one. and simply overwrite this method. Though I wasn't sure on the way to update the users image class options - to set :url_generator => NewSubClass, on the fly.

Cheers,

Tom

### CODE REVIEW

**Comment by larzconwell** [comment]
I wish this would get merged already. Thanks @tommeier

**Comment by larzconwell** [comment]
So I tried this in my application and i keep getting an error about 

`Undefined method '[]' for nil:NilClass` 

So I ran the resque worker rake task trace and It seems to be originating from this line in `lib/delayed_paperclip.rb`  `attachment_definitions[name][:delayed] = {}`

**Comment by tommeier** [comment]
Strange, I can't duplicate this? Are you sure its setup correctly in your app? Does the 2.4.5.1 version work?

**Comment by larzconwell** [comment]
Yeah I'm pretty sure it's setup correctly, I've went through the docs for it multiple times to make sure!

2.4.5.1 doesn't work for me an error about most_appropriate_url. 

I have Paperclip 2.7 with Redis 2.4.8 and Rails 3.2.2

**Comment by tommeier** [comment]
Try with Paperclip 2.4.5 and 2.4.5.1 for delayed_paperclip, just want to see if it is an introduced bug in the fork, or preexisting.

I have seen a similar error and, from memory, it was to do with the ordering of the paperclip styles in the model, and the line to say "process_in_background", make sure the paperclip declaration is before this line.

**Comment by larzconwell** [comment]
Ah! That's what was wrong! I had the `process_in_background` call before `has_attached_file`. The workers start up now!

**Comment by tommeier** [comment]
Hmm.. this is having issues for me. Researching now, it is saving as a different file name location, and not updating the file identifier on S3 saves. Locally it works fine.

**Comment by larzconwell** [comment]
That's kind of weird. I can only test locally for now, and it works fine for me. Also I was using the :hash for paperclip and delayed_paperclip was recreating the hash. I saw an issue on that but it was never resolved..

**Comment by tommeier** [comment]
Give up for now, i have a workaround, though its not elegant.

2 main issues : 
1 - Paperclip reprocess command, maintains the old `original` image, copies to a new one, then delayed_paperclip picks this up and generates other thumbnails. This leaves an orphaned image original (the largest). Especially on S3 this consumes a lot of space!

2 - When a slower queue, or S3 picks up the slack, the URL is different to the one that is saved, because it is based upon the :updated_at wildcard, which comes up as "Access Denied" S3 errors. The only way around this, that i've found so far, is to save upon end of reprocess task. Timestamps need to be updated. OR if you comment out : 
https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/attachment.rb#L317
in paperclip, it all works fine too.

Suffice to say, both rather nasty, both tricky, might look at making the switch to CarrierWave as the code seems a lot tighter than tying into a `reprocess` command (which has a comment in the paperclip to not use it).

**Comment by tommeier** [comment]
Note - This workaround should only be used if you are _not_ using after_save / after_update callbacks, or if you do, be aware they may be triggered twice.

**Comment by larzconwell** [comment]
I was thinking about moving to CarrierWave too, but this looks to work for now, thanks!

**Comment by tommeier** [comment]
Got it. Finally. 

See : https://github.com/jstorimer/delayed_paperclip/pull/62

**Pull request closed without merging**
